export type StoreCategory = 'course' | 'template' | 'service'

export type StoreProduct = {
  id: string
  slug: string
  name: string
  description: string
  price?: number
  category: StoreCategory
  image: string
  link: string
  locale: string
  featured: boolean
  dateAdded: string
}

export const STORE_PRODUCTS: StoreProduct[] = [
  // EN products
  {
    id: '1',
    slug: 'nextjs-saas-starter',
    name: 'Next.js SaaS Starter Kit',
    description: 'Production-ready starter with auth, payments, and dashboard. Built with Next.js 15, Drizzle, and Stripe.',
    price: 149,
    category: 'template',
    image: '/images/projects/astralyn/cover.png',
    link: 'https://example.com/nextjs-saas',
    locale: 'en',
    featured: true,
    dateAdded: '2025-01-15',
  },
  {
    id: '2',
    slug: 'react-mastery-course',
    name: 'React & Next.js Mastery',
    description: 'From fundamentals to advanced patterns. Covers hooks, server components, and production deployment.',
    price: 99,
    category: 'course',
    image: '/images/projects/captions-ai/cover.png',
    link: 'https://example.com/react-course',
    locale: 'en',
    featured: true,
    dateAdded: '2025-02-01',
  },
  {
    id: '3',
    slug: 'landing-page-service',
    name: 'Custom Landing Page',
    description: 'High-converting landing page with animations, forms, and analytics. 2-week delivery.',
    category: 'service',
    image: '/images/projects/spectrum-store/cover.png',
    link: 'https://example.com/landing',
    locale: 'en',
    featured: false,
    dateAdded: '2025-01-20',
  },
  {
    id: '4',
    slug: 'dashboard-template',
    name: 'Admin Dashboard Template',
    description: 'Modern admin UI with tables, charts, and dark mode. Tailwind + shadcn/ui.',
    price: 79,
    category: 'template',
    image: '/images/projects/chat-whizz/cover.png',
    link: 'https://example.com/dashboard',
    locale: 'en',
    featured: true,
    dateAdded: '2025-02-10',
  },
  {
    id: '5',
    slug: 'saas-architecture-course',
    name: 'SaaS Architecture Workshop',
    description: 'Learn to architect scalable SaaS products. Database design, APIs, and deployment strategies.',
    price: 129,
    category: 'course',
    image: '/images/projects/discord-clone/cover.png',
    link: 'https://example.com/saas-workshop',
    locale: 'en',
    featured: false,
    dateAdded: '2025-01-25',
  },
  {
    id: '6',
    slug: 'web-app-development',
    name: 'Full-Stack Web App Development',
    description: 'End-to-end development of web applications. React, Node.js, and PostgreSQL.',
    category: 'service',
    image: '/images/projects/astralyn/cover.png',
    link: 'https://example.com/web-app',
    locale: 'en',
    featured: false,
    dateAdded: '2025-02-05',
  },
  {
    id: '7',
    slug: 'portfolio-template',
    name: 'Developer Portfolio Template',
    description: 'Minimal portfolio template with blog, projects, and contact. Fully customizable.',
    price: 49,
    category: 'template',
    image: '/images/projects/spectrum-store/cover.png',
    link: 'https://example.com/portfolio',
    locale: 'en',
    featured: false,
    dateAdded: '2025-02-15',
  },
  {
    id: '8',
    slug: 'consulting-hour',
    name: 'Technical Consulting',
    description: '1-hour consulting session. Code review, architecture advice, or technical strategy.',
    price: 150,
    category: 'service',
    image: '/images/projects/captions-ai/cover.png',
    link: 'https://example.com/consulting',
    locale: 'en',
    featured: false,
    dateAdded: '2025-02-20',
  },
  // AR products
  {
    id: '9',
    slug: 'nextjs-saas-starter-ar',
    name: 'مجموعة بدء SaaS بـ Next.js',
    description: 'مجموعة جاهزة للإنتاج تتضمن المصادقة والمدفوعات ولوحة التحكم. مبنية بـ Next.js 15 و Drizzle و Stripe.',
    price: 149,
    category: 'template',
    image: '/images/projects/astralyn/cover.png',
    link: 'https://example.com/nextjs-saas',
    locale: 'ar',
    featured: true,
    dateAdded: '2025-01-15',
  },
  {
    id: '10',
    slug: 'react-mastery-course-ar',
    name: 'إتقان React و Next.js',
    description: 'من الأساسيات إلى الأنماط المتقدمة. يشمل الـ hooks ومكونات الخادم والنشر للإنتاج.',
    price: 99,
    category: 'course',
    image: '/images/projects/captions-ai/cover.png',
    link: 'https://example.com/react-course',
    locale: 'ar',
    featured: true,
    dateAdded: '2025-02-01',
  },
  {
    id: '11',
    slug: 'landing-page-service-ar',
    name: 'صفحة هبوط مخصصة',
    description: 'صفحة هبوط عالية التحويل مع رسوم متحركة ونماذج وتحليلات. تسليم خلال أسبوعين.',
    category: 'service',
    image: '/images/projects/spectrum-store/cover.png',
    link: 'https://example.com/landing',
    locale: 'ar',
    featured: false,
    dateAdded: '2025-01-20',
  },
  {
    id: '12',
    slug: 'dashboard-template-ar',
    name: 'قالب لوحة تحكم إدارية',
    description: 'واجهة إدارية حديثة مع جداول ورسوم بيانية والوضع الداكن. Tailwind و shadcn/ui.',
    price: 79,
    category: 'template',
    image: '/images/projects/chat-whizz/cover.png',
    link: 'https://example.com/dashboard',
    locale: 'ar',
    featured: true,
    dateAdded: '2025-02-10',
  },
  {
    id: '13',
    slug: 'saas-architecture-course-ar',
    name: 'ورشة هندسة SaaS',
    description: 'تعلّم تصميم منتجات SaaS قابلة للتوسع. تصميم قواعد البيانات وواجهات API واستراتيجيات النشر.',
    price: 129,
    category: 'course',
    image: '/images/projects/discord-clone/cover.png',
    link: 'https://example.com/saas-workshop',
    locale: 'ar',
    featured: false,
    dateAdded: '2025-01-25',
  },
  {
    id: '14',
    slug: 'web-app-development-ar',
    name: 'تطوير تطبيقات ويب كاملة',
    description: 'تطوير شامل لتطبيقات الويب. React و Node.js و PostgreSQL.',
    category: 'service',
    image: '/images/projects/astralyn/cover.png',
    link: 'https://example.com/web-app',
    locale: 'ar',
    featured: false,
    dateAdded: '2025-02-05',
  },
  {
    id: '15',
    slug: 'portfolio-template-ar',
    name: 'قالب محفظة المطور',
    description: 'قالب محفظة بسيط مع مدونة ومشاريع وتواصل. قابل للتخصيص بالكامل.',
    price: 49,
    category: 'template',
    image: '/images/projects/spectrum-store/cover.png',
    link: 'https://example.com/portfolio',
    locale: 'ar',
    featured: false,
    dateAdded: '2025-02-15',
  },
  {
    id: '16',
    slug: 'consulting-hour-ar',
    name: 'استشارة تقنية',
    description: 'جلسة استشارية لمدة ساعة. مراجعة كود أو نصائح هندسية أو استراتيجية تقنية.',
    price: 150,
    category: 'service',
    image: '/images/projects/captions-ai/cover.png',
    link: 'https://example.com/consulting',
    locale: 'ar',
    featured: false,
    dateAdded: '2025-02-20',
  },
]
